// src/redux/actionTypes.js
export const FETCH_CAFE_REQUEST = 'FETCH_CAFE_REQUEST';
export const FETCH_CAFE_SUCCESS = 'FETCH_CAFE_SUCCESS';
export const FETCH_CAFE_FAIL = 'FETCH_CAFE_FAIL';
export const ADD_REVIEW = 'ADD_REVIEW';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL';